# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20180223_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
