# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20180223_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
